services:
  ignition:
    image: gazebo:dev
    privileged: true
    container_name: gazebo_container
    network_mode: host
    runtime: nvidia # Commend down all runtime + deploy if you dont have gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./src:/workspaces/gazebo_ws/src:rw
      - workspace:/workspaces/gazebo_ws
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: bind
        source: /home/forev
        target: /home/forev
    environment:
      - XAUTHORITY
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    #command: ros2 launch p3at_description display.launch.py
    command: ros2 launch p3at_description nav2.launch.py
    #command: ros2 launch p3at_description map.launch.py
    
    tty: true
    stdin_open: true

  control_node:
    image: gazebo:dev
    privileged: true
    container_name: image_node
    network_mode: host
    runtime: nvidia # Commend down all runtime + deploy if you dont have gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./src:/workspaces/gazebo_ws/src:rw
      - workspace:/workspaces/gazebo_ws
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: bind
        source: /home/forev
        target: /home/forev
    environment:
      - XAUTHORITY
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    #command: ros2 launch p3at_description display.launch.py
    command: ros2 run control_package image_node
    
    tty: true
    stdin_open: true
  
    
volumes:
  workspace:
